# Generated by Django 4.0.4 on 2022-05-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='media/no_image.png', upload_to='products/%Y/%m/%d'),
        ),
    ]
